### ISSUE TITLE
Peripheral vascular disease - regex patterns

### ISSUE THREAD

**Issue by francisco003** [ellessenne/comorbidity#10]
Hello, 

I was comparing this packaged with a package in STATA (http://fmwww.bc.edu/RePEc/bocode/c/charlson.html) and something was different. 

In the "Internal Dataset #1: List of regex patterns", ICD-9-CM (comorbidity/data-raw/make-data.R), there is one code that i think is not correct, that is from the group Peripheral vascular disease, there is a code 47.1. 

This code is also present in the paper Coding algorithms for defining comorbidities in ICD-9-CM and ICD-10 administrative data, Quan H (https://www.ncbi.nlm.nih.gov/pubmed/16224307). 
But if you check the code it don't seem to be the write one.
447.1 - http://icd9.chrisendres.com/index.php?srchtype=diseases&srchtext=447.1&Submit=Search&action=search
47.1 - http://icd9.chrisendres.com/index.php?srchtype=diseases&srchtext=47.1&Submit=Search&action=search
 I think is missing a 4. The correct one is not 447.1? 

In this table (http://mchp-appserv.cpe.umanitoba.ca/concept/Charlson%20Comorbidities%20-%20Coding%20Algorithms%20for%20ICD-9-CM%20and%20ICD-10.pdf), is the code 447.1 instead of 47.1. 
And in the STATA package that i was comparing the results they also use the 447.1. 

There is other thing that is missing: 
Also in the same file mention above in: 
`lofregex[["charlson"]][["icd9"]][["copd"]] <- "^4168|^4169|^490|^491|^492|^493|^494|^495|^496|497|^498|^499|^500|^501|^502|^503|^504|^505|^5064|^5081|^5088"`

Is missing a "^" before the code: 497

try this to examples: 
id  |  code 
1   |  497
2   |  V497

**Comment by ellessenne** [comment]
Hello!
First of all, sorry for the delayed response.
I had a look into it, and it looks like the paper by Quan _et al_. had a typo - the list of codes for the Elixhauser comorbidity score reports the correct code, 447.1.
I will merge the pull request by @salmasian (thanks, by the way!) and I will push an update to CRAN ASAP.
Also, thanks for spotting the small bug with the regex pattern!

Alessandro

**Comment by francisco003** [comment]
Hello,

No problem =)
Thanks for replying to my email.
Keep the good work.

Francisco



________________________________
De: Alessandro Gasparini <notifications@github.com>
Enviado: 27 de junho de 2019 12:13
Para: ellessenne/comorbidity
Cc: francisco003; Author
Assunto: Re: [ellessenne/comorbidity] Peripheral vascular disease - regex patterns (#10)


Hello!
First of all, sorry for the delayed response.
I had a look into it, and it looks like the paper by Quan et al. had a typo - the list of codes for the Elixhauser comorbidity score reports the correct code, 447.1.
I will merge the pull request by @salmasian<https://github.com/salmasian> (thanks, by the way!) and I will push an update to CRAN ASAP.
Also, thanks for spotting the small bug with the regex pattern!

Alessandro
