### ISSUE TITLE
Possible speed increase

### ISSUE THREAD

**Issue by jwilliman** [ellessenne/comorbidity#13]
Hello

This package is great, and saved me doing a lot of coding. I have some suggestions that could significantly increase its speed. The main idea relies on the assumption that each code only relates to one comorbidity (I believe this is true?) In which case; 
1. The codes can be replaced by their comorbidity group name (or dropped). The quickest way to do this is to transform the code variable to a factor and then replace the levels of the factor using regex matching (rather than checking every code individually).
2. The replaced variable is then transposed from long to wide. 

```

## Load libraries
library(comorbidity)
library(data.table)
library(tictoc)

## User function to replace factor levels using regex matching
### 'replace' must be a named list of regex codes, unmatched codes are dropped.
xfactor <- function(x, replace) {
  
  x <- factor(x)
  levels_tmp <- levels(x)
  for(i in seq_along(replace)) 
    levels_tmp[grepl(replace[i], levels_tmp)] <- names(replace)[i]
  levels(x) <- levels_tmp
  x <- factor(x, levels = names(regex))  
  
}

## Create example dataset
### Number of patients
n_ids <- 100000
### Average number of codes per patient
n_codes <- 10

set.seed(1)
dfr <- data.frame(
  id = sample(1:n_ids, size = n_ids * n_codes, replace = TRUE),
  code = sample_diag(n_ids * n_codes),
  stringsAsFactors = FALSE
)

dfr <- dfr[order(dfr$id),]

### Set options
id = "id"
code = "code"
score = "charlson"
icd = "icd10"
regex <-  comorbidity:::lofregex[[score]][[icd]]

## Using current scoring algorithm
tictoc::tic()
### Split by ID
x1 <- utils::unstack(dfr, form = stats::as.formula(paste(code, id, sep = "~")))
### Run scoring algorithm
x1 <- comorbidity:::.score(x1, id = id, score = score, icd = icd, parallel = TRUE, mc.cores = 4)
x1[,-1] <- lapply(x1[,-1], as.integer)
tictoc::toc()
52.33 sec elapsed

## New algorithm using base R
x2 <- dfr
tictoc::tic()
x2$code_f <- xfactor(x = x2[, code], replace = regex)
x2 <- unique(x2[, c(id, "code_f")])
x2 <- reshape2::dcast(x2, id ~ code_f, length, value.var = "code_f", fill = 0)
x2$`NA` <- NULL
x2[, id] <- as.character(x2[, id])
x2[,-1] <- lapply(x2[,-1], as.integer)
tictoc::toc()
12.67 sec elapsed

identical(x1, x2)
[1] TRUE

## A further gain of speed using the data.table package
x3 <- dfr

tictoc::tic()
setDT(x3)
x3[, code_f := xfactor(x3[, code], regex)]
x3 <- dcast.data.table(unique(x3[, .(id, code_f, value = 1L)]), id ~ code_f, fill = 0)
x3[, `NA` := NULL]
x3[, id := as.character(id)]
setDF(x3)
tictoc::toc()
0.57 sec elapsed

identical(x1, x3)
[1] TRUE
```

**Comment by salmasian** [comment]
I am a big fan of `data.table` myself but I want to point out that what you proposed above means a dependency to `data.table` would be created.

**Comment by jwilliman** [comment]
True, that is why I suggested a base R approach as well. In my code above I used the `reshape2` package because I though the code was cleaner than using `base::reshape`. But I have discovered that a pure `base` approach actually ends up being almost as fast as the `data.table` approach. 

```
x4 <- dfr

tictoc::tic()
### Convert code to factor and replace codes with comorbidity names
x4$code_f <- xfactor(x = x4[, code], replace = regex)

### Drop records without any comorbidities and collapse duplicate comorbidities.
x4_w <- unique(x4[!is.na(x4$code_f), c(id, "code_f")])

### Reshape data wide, correct order and names of comorbidity variables 
x4_w <- x4_w[order(x4_w[, id]),]
x4_w$flag <- 1L
x4_w <- reshape(x4_w, idvar = id, timevar = "code_f", direction = "wide", sep = "_")
names(x4_w) <- gsub("flag_", "", names(x4_w))
x4_w <- x4_w[, c(id, names(regex))]

### Add back in records without any comorbidities, set NA values to 0.
x4 <- merge(unique(x4[, id, drop = FALSE]), x4_w, by = id, all.x = TRUE)
x4[is.na(x4)] <- 0L

### 
x4[, id] <- as.character(x4[, id])

tictoc::toc()
1.72 sec elapsed

identical(x1, x4)
[1] TRUE

```

It is possible that this `base` approach is the default, with the `data.table` approach only used if the input dataset is a`data.table`.

**Comment by ellessenne** [comment]
Hello @jwilliman,
thanks for your contribution - this is excellent!
Exploring speed benefits by using `data.table` was definitely on my to-do list, and I am glad that you showed it actually delivers.
I wouldn't mind adding the `data.table` dependency (as it doesn't bring anything else in), but I need to do some further testing first.
July is going to be a hell of a month, but give me some time and I'll implement the changes you suggest; in the meanwhile, would you mind adding yourself as a contributor (by editing the DESCRIPTION file - you can do it directly from GitHub)?

**Comment by ellessenne** [comment]
Hi, coming back with a quick update.
I managed to see what it takes to implement this method, and it is actually straightforward.
The only problem is, some comorbidity domains (e.g. Charlson with ICD9-CM, and Elixhauser comorbidity scores) include overlapping codes (e.g. codes that appear in multiple comorbidity domains): this approach based on factors does not work in these settings, as it can only accommodate a single domain per code. 
Any idea on how to do so with this algorithm?

**Comment by ellessenne** [comment]
Hi again - I managed to implement an algorithm that actually works as expected and that is faster than the current - although not as fast as the one you suggest.

Here is the current approach, and the `data.table` approach that you suggest:

``` r
## Load libraries
library(comorbidity)
library(data.table)
library(tictoc)

## User function to replace factor levels using regex matching
### 'replace' must be a named list of regex codes, unmatched codes are dropped.
xfactor <- function(x, replace) {
  x <- factor(x)
  levels_tmp <- levels(x)
  for (i in seq_along(replace)) {
    levels_tmp[grepl(replace[i], levels_tmp)] <- names(replace)[i]
  }
  levels(x) <- levels_tmp
  x <- factor(x, levels = names(regex))
}

## Create example dataset
### Number of patients
n_ids <- 100000
### Average number of codes per patient
n_codes <- 10

set.seed(1)
dfr <- data.frame(
  id = sample(seq(n_ids), size = n_ids * n_codes, replace = TRUE),
  code = sample_diag(n_ids * n_codes),
  stringsAsFactors = FALSE
)

dfr <- dfr[order(dfr$id), ]

### Set options
id <- "id"
code <- "code"
score <- "charlson"
icd <- "icd9"
regex <- comorbidity:::lofregex[[score]][[icd]]

## Using current scoring algorithm
tictoc::tic()
### Split by ID
x1 <- utils::unstack(dfr, form = stats::as.formula(paste(code, id, sep = "~")))
### Run scoring algorithm
x1 <- comorbidity:::.score(x1, id = id, score = score, icd = icd, parallel = TRUE, mc.cores = 4)
x1[, -1] <- lapply(x1[, -1], as.integer)
tictoc::toc()
#> 42.375 sec elapsed

## A further gain of speed using the data.table package
x3 <- dfr

tictoc::tic()
setDT(x3)
x3[, code_f := xfactor(x3[, code], regex)]
x3 <- dcast.data.table(unique(x3[, .(id, code_f, value = 1L)]), id ~ code_f, fill = 0L)
x3[, id := as.character(id)]
setDF(x3)
# Remove NA column
if ("NA" %in% names(x3)) x3[["NA"]] <- NULL
# Augment with comorbidities not detected (if so), and order columns
x3[, names(regex)[!names(regex) %in% names(x3)]] <- 0L
x3 <- x3[, c(id, names(regex))]
tictoc::toc()
#> 0.619 sec elapsed

identical(x1, x3)
#> [1] TRUE
```

I tried a plain `data.table` approach, but it results slower than the current one:

```r
### Plain data.table approach
x2 <- dfr

tictoc::tic()
data.table::setDT(x2)
x2[, id := as.character(id)]
x2[, names(regex) := lapply(X = names(regex), FUN = function(w) {
  max(grepl(regex[[w]], code))
}), by = id]
x2[, code := NULL]
x2 <- unique(x2, by = key(id))
data.table::setDF(x2)
tictoc::toc()
#> 76.521 sec elapsed

identical(x1, x2)
#> [1] TRUE
```

Finally, I thought about using the idea of removing all observations with not-maching codes to turn the problem into a much smaller one.
This works quite well, and it is much faster than the current approach:

```r
x4 <- dfr
.add_missing <- function(id, regex) {
  out <- data.table::data.table(id = id)
  out[, names(regex) := 0L]
  return(out)
}

tictoc::tic()
id.list <- unique(x4[[id]])
data.table::setDT(x4)
x4 <- unique(x4)
x4[, code_f := xfactor(x4[, code], regex)]
x4 <- x4[!is.na(code_f), ]
x4[, code_f := NULL]
x4[, names(regex) := lapply(X = names(regex), FUN = function(w) max(grepl(regex[[w]], code))), by = id]
x4[, code := NULL]
x4 <- unique(x4, by = key(id))
x4 <- rbindlist(list(x4, .add_missing(id = id.list[!(id.list %in% x4[[id]])], regex = regex)), use.names = TRUE)
x4 <- x4[order(id)]
x4[, id := as.character(id)]
data.table::setDF(x4)
x4[, -1] <- lapply(x4[, -1], as.integer)
tictoc::toc()
#> 1.409 sec elapsed

identical(x1, x4)
#> [1] TRUE
```

I implemented the new approach in a separate branch for testing; it can be installed with:

```r
remotes::install_github("ellessenne/comorbidity", ref = "#13")
```

If you could give it a go, that would be great. Thanks!

**Comment by jwilliman** [comment]
Hi

Its taken me a while to look at this. Given your comments around one diagnosis matching multiple comorbidities, I wondered if it might be easier to merge a `data.frame` with all the possible codes and associated comorbidities. Happily, the process of creating such a `data.frame` can be partially automated.

In base R (with reshape2)

```

x5 <- dfr
setDF(x5)

tic()

## Get list of unique codes used in dataset that match comorbidities
list_codes_all <- sapply(regex, grep, unique(x5$code), value = TRUE)

## Convert list to data.frame of all codes used and relevant comorbidity
dt_codes_all   <- reshape2::melt(list_codes_all, value.name = "code")

## Merge list with original data.frame, dropping rows without comorbidities
x5l <- merge(x5, match_dt)

### Reshape data wide, and correct order and names of comorbidity variables 
x5l <- unique(x5l[order(x5l[, id]), c("id", "L1")])
x5l$flag <- 1L
x5_w <- reshape(x5l, idvar = id, timevar = "L1", direction = "wide", sep = "_")
names(x5_w) <- gsub("flag_", "", names(x5_w))
x5_w <- x5_w[, c(id, names(regex))]

### Add back in records without any comorbidities, set NA values to 0.
x5 <- merge(unique(x5[, id, drop = FALSE]), x5_w, by = "id", all.x = TRUE)
x5[is.na(x5)] <- 0L

### Would still need to add in any comorbidities that no-one has.

### 
x5[, id] <- as.character(x5[, id])

toc()
2.42 sec elapsed

```

Or using `data.table`

```

x6 <- dfr
setDT(x6)

tic()

## Get list of unique codes used in dataset that match comorbidities
list_codes_all <- sapply(regex, grep, unique(x6$code), value = TRUE)

## Convert list to data.table of all codes used and relevant comorbidity
dt_codes_all   <- data.table::melt(list_codes_all, value.name = "code")

## Merge list with original data.table (data.frame) 
x6l <- unique(merge(x6, match_dt, 
             all.x = TRUE, allow.cartesian = TRUE)[, code := NULL])

## Spread list wide.
x6_w <- dcast.data.table(x6l[, .(id, L1, value = 1L)], id ~ L1, fill = 0)

## Clean up resulting data.table.
x6_w[, `NA` := NULL]
setcolorder(x6_w, c("id", names(regex)))
set(x6_w, j="id", value=as.character(x6_w$id))

toc()
0.96 sec elapsed

```
I had a go with your approach above, and it appears that the above two examples are quicker.

(Not sure how to get my code to appear in colour?!)

**Comment by ellessenne** [comment]
Hello again @jwilliman and thanks for looking into this.
I will have a go with your new approach and keep you posted!

P.s.: you can correct syntax highlighting by defining the language at the beginning of the code chunk, e.g. for R:

```
```r
```

**Comment by ellessenne** [comment]
@jwilliman I cannot re-run your example code, as `match_dt` is missing (or not defined).
Could you paste a fully reproducible example by any chance?

**Comment by jwilliman** [comment]
Apologies. That should have been `dt_codes_all`. Have corrected above.

**Comment by Chris-M-P** [comment]
Just chipping in to say these have given an astonishing speed boost to my work involving ~200m ICD10 codes across ~40m hospital episodes. Time taken to calculate Charlson comorbidity is now down from ~11 hours to 3-4 minutes

**Comment by ellessenne** [comment]
Hi all,
I got some time to implement the latest algorithm (#13v2 branch) and do some testing, I think I'll merge it soon.
See the results of my testing below:

![plot](https://user-images.githubusercontent.com/10330005/62693298-206c1f80-b9ca-11e9-95bf-7e520a267119.png)

@jwilliman, would you like to add yourself as a contributor in the DESCRIPTION file (if you wish)?
