### ISSUE TITLE
ahrq score calculation appears incorrect

### ISSUE THREAD

**Issue by cornflakegrl** [ellessenne/comorbidity#14]
Calculated score should be: 9 (chf) - 1 (hypc) + 4 (hypothy) = 12
R output:
PT_ID	chf	carit	valv	pcd	pvd	hypunc	hypc	para	ond	cpd	diabunc	diabc	hypothy	rf	ld	pud	aids	lymph	metacanc	solidtum	rheumd	coag	obes	wloss	fed	blane	dane	alcohol	drug	psycho	depre	wscore_ahrq	wscore_vw
13	1	0	0	0	0	0	1	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	8	7

**Comment by ellessenne** [comment]
Hypothyroidism has a weight of zero in the AHRQ Elixhauser comorbidity score, please see [Moore _et al_., 2017](https://www.ncbi.nlm.nih.gov/pubmed/28498196).

**Comment by cornflakegrl** [comment]
I am going by your documentation on https://cran.r-project.org/web/packages/comorbidity/vignettes/comorbidityscores.html
![image](https://user-images.githubusercontent.com/52292894/60598112-c1374180-9d71-11e9-87a6-600241600805.png)

**Comment by ellessenne** [comment]
That's a typo in the vignette, thanks for reporting it!
