### ISSUE TITLE
weights for Charlson calc

### ISSUE THREAD

**Issue by DougDame** [ellessenne/comorbidity#17]
The doco says this on **WEIGHTS**:

"Each condition from the Charlson score is assigned a score when computing the weighted Charlson index, irrespectively of the coding system utilised. In particular, diabetes with complications, hemiplegia/paraplegia, renal disease, and malignancies are assigned a score of 2; moderate/severe liver disease is assigned a score of 3; metastatic solid tumour and AIDS/HIV are assigned a score of 6; the remaining comorbidities are assigned a score of 1. comorbidity allows the option of applying a hierarchy of comorbidities should a more severe version be present: by choosing to do so (and that is the default behaviour of comorbidity) a type of comorbidity is never computed more than once for a given patient."

Those are the weights generally used before Quan et al updated the ICD-code lists and derived new weights from a newer and much larger dataset, as shown below. The AIDS/HIV @ 6 was the clue that I first noticed. 

![image](https://user-images.githubusercontent.com/18072463/62838880-0d6a8100-bc50-11e9-87d1-f909dc6c41ac.png)

My thought is that the Quan weights should at least be an option. Making it the default at this point might be disruptive to existing users. 

Doug

**Comment by ellessenne** [comment]
Hello @DougDame,
Thanks for the feedback. Do you have a reference for the updated scoring algorithm?
Thanks!

**Comment by DougDame** [comment]
The table above is from:

![image](https://user-images.githubusercontent.com/18072463/62996491-ea4bf700-be32-11e9-842d-21ed3e1aca59.png)


... which I thought was excellent work when it first appeared, and still do.

HTH - d.d.

**Comment by ellessenne** [comment]
Thanks for the reference @DougDame!

**Comment by torema-ed** [comment]
Hi @ellessenne, my colleague [(**@SY-CHIA**)](https://github.com/SY-CHIA) have also done this in the code snippets mentioned in #36. I integrate it into the package and file a PR if it is ok with you.

**Comment by ellessenne** [comment]
I am closing this, as it is now implemented in the GitHub version of {comorbidity}. Will make it to CRAN ASAP.
