### ISSUE TITLE
Input cannot be a data.table

### ISSUE THREAD

**Issue by salmasian** [ellessenne/comorbidity#23]
This works:

```r
dt <- data.frame(
  EncID = 1234,
  DxCode = 'N390'
)

comorbidity(dt, id = 'EncID', code = 'DxCode', icd = 'icd10', score = 'charlson', assign0 = F)
```

But this does not:

```r
dt <- data.table(
  EncID = 1234,
  DxCode = 'N390'
)

comorbidity(dt, id = 'EncID', code = 'DxCode', icd = 'icd10', score = 'charlson', assign0 = F)
```

Note that data.tables are inherently a data.frame too, yet somehow the latter causes the following error message:

```
Error in data.table::setDT(x) : 
  Argument 'x' to 'setDT' should be a 'list', 'data.frame' or 'data.table'
```

Using data.table version 1.12.6 and comorbidity 0.5.2

**Comment by ellessenne** [comment]
Hi Hojjat,
Thanks for reporting this. 
It should now be fixed in the development version on GitHub, could you give it a try?

**Comment by salmasian** [comment]
Yes, it works now. Thanks for the quick fix!
