### ISSUE TITLE
The assign0 argument should either have a default or come before the icd argument

### ISSUE THREAD

**Issue by salmasian** [ellessenne/comorbidity#24]
The current signature for the `comorbidity()` function is as follows:

```
comorbidity(x, id, code, score, icd = "icd10", assign0, factorise = FALSE, labelled = TRUE, tidy.codes = TRUE)
```

This is bad practice. All arguments that are mandatory (i.e. have no default) should come first, and all arguments with a default should come next. Either a default should be set for the `assign0` argument or it should come before the `icd` argument. My personal vote: assign a default value of FALSE to `assign0`.

**Comment by ellessenne** [comment]
Hi, I had a long discussion over e-mail with some users and decided to not have a default for the `assign0` argument - this forces the user to make a decision about it. I prefer leaving it this way.
I wouldn't mind changing the order of the arguments (it doesn't really matter to me), but - just out of curiosity - where did you read that the way it is now is bad practice?

**Comment by salmasian** [comment]
I am looking to find documentation on it, but in the meantime, let me explain the reasoning:

Just because a function's arguments are named it doesn't mean you have to specify the name when you call the function. For a function like `foo <- function(x, y)` you don't need to call it as `foo(x = 1, y = 100)` and can simply call it as `foo(1, 100)`. This also applies when some arguments of the function have a default value. For a function like `bar <- function(x, y = 0)` all of these are valid calls and will give the same result: `bar(1, 0)`, `bar(x = 1, y = 0)`, `bar(1)`, `bar(x = 1)`. Note that in the last two examples, the user only provides the value for arguments without a default. Everything I said so far is super obvious, but I needed to say to motivate the next sentences.

The whole idea of having default values for some arguments is that you should be able to call a function by only providing values for arguments without a default. But if I call `comorbidity(data, 'id', 'diag', 'charlson', TRUE)` it won't work. I provided five values, and there are five arguments with no default, but because the `icd` argument is defined prior to the `assign0` argument, R will use the value `TRUE` for the `icd` argument, not the `assign0` argument, and I will get an error: 

```
> comorbidity(data, 'id', 'diag', 'charlson', TRUE)
Error in checkmate::assert_logical(assign0, len = 1, add = arg_checks) : 
  argument "assign0" is missing, with no default
```

**Comment by salmasian** [comment]
I cannot find the documentation on it for R. But here are some for other languages:

* [Explanation on SO about JavaScript](https://stackoverflow.com/a/46960442)
* [Explanation on SO about C#](https://stackoverflow.com/questions/2896106)
* Microsoft's VB.Net documentation: "[Every parameter following an optional parameter in the procedure definition must also be optional.](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/optional-parameters)"

**Comment by ellessenne** [comment]
Thanks @salmasian, I had not thought about it.
It makes sense, I will modify the order of the arguments in the next release of `comorbidity`!
