### ISSUE TITLE
Possible typo in code for the Enhanced-ICD-9-CM Charlson Comorbidity Score algorithm

### ISSUE THREAD

**Issue by dwgarvert** [ellessenne/comorbidity#26]
I believe there may be a typo stemming from the Quan et al. paper from 2005 in the Enhanced-ICD-9-CM column of Table 1 for the coding algorithm of the Charlson Comorbidity Score under the Peripheral vascular disease comorbidity. The code in question is listed as "47.1", but I believe this may be a typo and should actually be "447.1". In the most recent ICD-9-CM code dataset, a code of "47.1" (or 0471) is listed as "Meningitis due to echo virus", while 447.1 (or 4471) is listed as "Stricture of artery", which appears to be a much more appropriate diagnosis under this particular comorbidity. If this has already been addressed, I apologize for posting this issue again. I noticed this potential error in the Quan et al. paper and also on the website here:
https://cran.r-project.org/web/packages/comorbidity/vignettes/comorbidityscores.html

**Comment by ellessenne** [comment]
Hi, the code should be ok (the typo in the Quan paper was reported in #10) but I must have forgotten to update the vignette. 
Will double-check and correct as soon as possible. 
Thanks!
