### ISSUE TITLE
Versions of ICD-10 codes

### ISSUE THREAD

**Issue by sg-peytrignet** [ellessenne/comorbidity#31]
Hi All,

Thank you for this excellent package. This is not a bug, just a question. Am I right in my understanding that the package currently identifies Elixhauser conditions based on the 2011 version of the ICD-10 codes? If the codes for something such as diabetes are now recorded with new codes, would this then prevent the comorbidity() function from identifying the condition?

Thanks

Sebastien

**Comment by ellessenne** [comment]
Hello,
Sorry for the delayed response, this must have slipped through my e-mails and just noticed this now!
Anyway, yeah, the default scores are based on the papers listed as references (e.g. the Quan et al. paper) - `comorbidity()` will only fail to identify new codes or codes that have changed between the ICD-10 revisions (which I am not sure of, I always assumed it was quite stable between minor revisions?).
