### ISSUE TITLE
Confusing result with assign0 set to True

### ISSUE THREAD

**Issue by rplzzz** [ellessenne/comorbidity#32]
Using comorbidity v. 0.5.3, I ran the following call:
```R
elixtbl <-
  comorbidity::comorbidity(
    x = dxtbl,
    id = "CLAIM_NO",
    code = "dxvals",
    score = "elixhauser",
    icd = 'icd10',
    assign0 = TRUE
  )
```
So, according to the documentation, I should expect (among other things) that `hypc` and `hypunc` are never both true.  However, when I look at the output, there are several such instances:
```
> head(elixtbl[ , c('hypc', 'hypunc')])
  hypc hypunc
1    1      1
2    0      1
3    1      0
4    1      1
5    1      1
6    1      1
```
In fact this seems to be the usual case:
```
> sum(elixtbl$hypc==1 & elixtbl$hypunc == 1) / sum(elixtbl$hypc==1)
[1] 0.8651381
```
This also seems to happen with the other two hierarchical conditions:
```
> sum(elixtbl$metacanc == 1 & elixtbl$solidtum) / sum(elixtbl$metacanc)
[1] 0.8641205
> sum(elixtbl$diabc==1 & elixtbl$diabunc==1) / sum(elixtbl$diabc)
[1] 0.4266899
```
Am I misunderstanding how the `assign0` argument is supposed to work?

**Comment by ellessenne** [comment]
Hi,
`assign0` actually only applies to the score obtained by combining the different domains, e.g. with `hypc` and `hypunc` only the former will contribute to the final Elixhauser score!
Each comorbidity domain is not affected (individually) by the `assign0` argument.
I hope this helps,

Alessandro

**Comment by rplzzz** [comment]
Thanks, that clears it up.  FWIW, this is a little unclear in the documentation. Would you be receptive to a patch?

Also, I will probably write for my own use a function to enforce the hierarchical constraint on the individual domains (I'm doing a mixed-effects model, so I need the individual values).  Would you be interested in supporting that as an option in the comorbidity function (e.g. by allowing `assign0` to have true/false/NA values)?

**Comment by ellessenne** [comment]
Yeah I am happy to edit the documentation if the default behaviour is not very clear! 😄 
Also, could you explain the latter suggestion a bit more into detail? I'm not sure what you mean, are you referring to the expected behaviour of `assign0` from your previous message or to something else?

(I also more often than not use individual domains by the way!)

**Comment by rplzzz** [comment]
Well, the way I see it, there are three plausible scenarios for someone using the package:
1. The user wants no hierarchy, just a raw tabulation and count of which conditions are coded.
2. The user wants a raw tabulation of which conditions are present, but wants the count to reflect hierarchical constraints.
3. The user wants both the tabulation and the count to reflect hierarchical constraints.

Currently the first two use cases are supported, but all three could be supported by having three different allowable values of `assign0`.

**Comment by ellessenne** [comment]
Hi @rplzzz, I pushed a new version to GitHub that modifies the behaviour of the `assign0` parameter.
Now, it accepts three values:

* `assign0 = "none"`, which corresponds to the previous `assign0 = FALSE` and does not apply a hierarchy of comorbidities;
* `assign0 = "score"`, which corresponds to the previous `assign0 = TRUE` and applies the hierarchy to scores (and weighted scores) only;
* `assign0 = "both"`, the new scenario, which applies the hierarchy to both comorbidity domains and scores (what we were discussing above).

Could you kindly give it a go by installing the dev version with:

```r
remotes::install_github("ellessenne/comorbidity")
```

Thanks and let me know.

Alessandro

**Comment by rplzzz** [comment]
Thanks, @ellessenne, I'll give it a try in the next few days.

(Sorry for the slow response; I've been slammed with other projects these past few weeks.)

**Comment by ellessenne** [comment]
No worries, I'm not in a rush anyway - I am thinking about the API as I'm not sure I'm 100% happy with the current implementation. Anyway, just let me know. Thanks!

**Comment by ellessenne** [comment]
I am closing this, the new API (#38) implements separate `assign0` arguments for the comorbidity identification and scoring algorithm parts. 
@rplzzz, if you could give it a go (whenever you have some time) it would be great.
Thanks!
