### ISSUE TITLE
Unable to access/modify variable labels

### ISSUE THREAD

**Issue by Chris-M-P** [ellessenne/comorbidity#39]
I would like to modify the variable labels (from the `labelled = TRUE` option) and include them in exported data through `haven` for Stata. Variable labels are showing up in the Rstudio viewer as expected, but I'm unable to find the attribute anywhere. Using the code below (modified from help file):

```
data10 <- data.frame(
  id = sample(1:10, size = 250, replace = TRUE),
  code = sample_diag(n = 250, version = "ICD10_2011"),
  stringsAsFactors = FALSE
)
data10 <- data10[order(data10$id), ]

elixhauser10 <- comorbidity(x = data10, 
                            id = "id", 
                            code = "code", 
                            score = "elixhauser", 
                            icd = "icd10",
                            labelled = "TRUE",
                            assign0 = FALSE)
str(elixhauser10)
```

I would expect this code: `attr(elixhauser10$id, "variable.labels")` to return "ID" (as is shown in the RStudio viewer), but instead returns "NULL". `attributes(elixhauser10$id)` similarly returns "NULL"

**Comment by Chris-M-P** [comment]
Ahh - I can see that the variable.labels attribute is at the dataframe level. This seems an unusual choice, and causes some conflicts if for example I derive multiple comorbidity scores.
Is it preferable to keep the variable.labels at the dataframe level?

I've got a workaround which pulls them down to the variable level:
```
for(i in seq_along(df)){
  if(!is.na(attr(df, "variable.labels")[i])){
     Hmisc::label(df[, i]) <- attr(df, "variable.labels")[i]
    }
}
```

**Comment by ellessenne** [comment]
Hi!
Yeah, to be honest the labels are only for the RStudio viewer, they were not intended to be Stata-style variable labels.
I would rather not introduce a dependency on {Hmisc}, as it's a pretty big package for a minor feature of {comorbidity}, but I am glad you found a workaround!
Regarding possible conflicts with multiple scores, wouldn't that be a problem anyway? I mean, some domains are named the same, so there would be some editing to do anyway?

**Comment by Chris-M-P** [comment]
That makes sense and I completely understand not wanting to add such a large package as a dependency. I simply modified the easiest solution from SO for my purposes! If I revisit this with base R I'll add the solution to this thread.

The conflicts between multiple scores happen when I merge dataframes with Elixhauser and Charlson scores together. In the example code below I append the ELixhauser variables with "_eh" and the Charlson with "_cci" to distinguish them. When I join the dataframes together the Elixhauser variable labels are retained, but the Charlson labels are lost. The converse happens if I reverse the order of the merge. This doesn't happen when I apply the variable labels as attributes of the variables rather than the dataframe. 

```
library(tidyverse)

data10 <- data.frame(
  id = sample(1:10, size = 250, replace = TRUE),
  code = sample_diag(n = 250, version = "ICD10_2011"),
  stringsAsFactors = FALSE
)
data10 <- data10[order(data10$id), ]

elixhauser10 <- comorbidity(x = data10, 
                            id = "id", 
                            code = "code", 
                            score = "elixhauser", 
                            icd = "icd10",
                            labelled = TRUE,
                            assign0 = FALSE) %>% 
  rename_with(.fn = ~paste0(., "_eh"), -"id")

charlson10 <- comorbidity(x = data10, 
                            id = "id", 
                            code = "code", 
                            score = "charlson", 
                            icd = "icd10",
                            labelled = TRUE,
                            assign0 = FALSE) %>% 
  rename_with(.fn = ~paste0(., "_cci"), -"id")


elixhauser10 %>% left_join(charlson10, by = "id") %>% View()
```

**Comment by ellessenne** [comment]
Sorry for the belated answer, but I understand the issue now – I tried the above and in fact there is a "clash".
However, I am not sure if there's a way to fix that that doesn't involve manually re-assigning labels?
