### ISSUE TITLE
getting "Error in data.table::setnames(x = loc, new = c(code, "ind")) :    When 'new' is provided, 'old' must be provided too"

### ISSUE THREAD

**Issue by gp-singh-hub** [ellessenne/comorbidity#45]
Dear colleague,

I am getting following error when running comorbiodity command:

comorbidity(x = x, id = "id", code = "code", map = "elixhauser_icd10_quan", assign0 = TRUE)

"Error in data.table::setnames(x = loc, new = c(code, "ind")) : 
  When 'new' is provided, 'old' must be provided too"

Please help

Thanks

**Comment by ellessenne** [comment]
Hi,
Not sure what is going on there – could you please provide a reproducible example, e.g. with the [{reprex}](https://reprex.tidyverse.org/index.html) package, to help debugging the issue?
In the meanwhile, I would suggest updating all your packages and try again.
Let me know if that works,

Alessandro

**Comment by gp-singh-hub** [comment]
Hello @ellessenne , it was an R version issue indeed. Updating R addressed the problem.
Thanks a lot for your help!

**Comment by ellessenne** [comment]
Awesome, glad it worked!
