### ISSUE TITLE
could not find function "score"

### ISSUE THREAD

**Issue by Flora-love-cat** [ellessenne/comorbidity#46]
When I tried to calculate the Charlson score by the following code in tutorial, it prompted `Error in score(charlson, weights = NULL, assign0 = FALSE) : could not find function "score"`. I wonder if the unweighted score calculated by `score` function is same as the `score` column in `Charlson` table?

```
unw_cci <- score(charlson, weights=NULL, assign0=FALSE)
```

**Comment by ellessenne** [comment]
Hi, 
I suspect you are following the code tutorial for the latest version of {comorbidity}, but have a previous one (where the `score()` function did not exist). I would suggest trying to `update.packages(ask = F)` all your packages and try again, hopefully it is a simple fix!

**Comment by ellessenne** [comment]
No worries, glad to hear it is now sorted!
