### ISSUE TITLE
Charlson comorbidity index conditions names

### ISSUE THREAD

**Issue by DrYan1102** [ellessenne/comorbidity#53]
Hi, there is a little detail I feel concerned. 

When I calculate the cases of comorbidities for each patient, I found COPD was in the CCI. However, according to Quan (2005), it should be Chronic pulmonary disease. On the other hand, I tested the codes of Chronic pulmonary disease and COPD as follow:
`df <- data.frame(id = c(1,2),code = c("J64","J441"))` where J64 does not belong to COPD, but the result still counted J64 as COPD, so I guess maybe it is just an error to put COPD which should have been in the Elixhauser score into the CCI, while the chronic pulmonary disease in the Elixhauser score should have been COPD .

I sincerely look forward to your reply. And thank you for your time.

**Comment by ellessenne** [comment]
Hi,
I updated some comorbidity names for the Charlson index on a separate branch, could you give it a try and see if it is now clearer:

```r
library(remotes)
remotes::install_github("ellessenne/comorbidity", ref = "#53")
```

Thanks,

Alessandro

**Comment by DrYan1102** [comment]
> Hi, I updated some comorbidity names for the Charlson index on a separate branch, could you give it a try and see if it is now clearer:
> 
> ```r
> library(remotes)
> remotes::install_github("ellessenne/comorbidity", ref = "#53")
> ```
> 
> Thanks,
> 
> Alessandro

Hi Alessandro,

Thanks for the contact. I just tried the new version of package, it worked. However, I also feel sorry to failed to point another thing out before. I noticed ami (acute myocardial infarction) is in Charlson comorbidity score. I checked the Quan (2005) again and I found he used MI (myocardial infarction) and I tried the codes of chronic myocardial infarction with I252 in the comorbidity( ). As a result, the it was also counted as acute myocardial infarction, so I guess maybe the ami was made in the first version of this package, too. 

I look forward to your reply and thank you for your time!

Kaiwei

**Comment by DrYan1102** [comment]
> Hi, I updated some comorbidity names for the Charlson index on a separate branch, could you give it a try and see if it is now clearer:
> 
> ```r
> library(remotes)
> remotes::install_github("ellessenne/comorbidity", ref = "#53")
> ```
> 
> Thanks,
> 
> Alessandro

Sorry to remind you again. I just found a little detail, but I don't know the reason. 

When I only use `comorbidity(x = y, id = "id", code = "code",
            map = "charlson_icd10_quan", assign0 = FALSE)`, the result showed cpd, 

but when I made it an object as follows,
`y <- data.frame(id = c(1,2),code = c("I252", "I211"))`
```
z <- comorbidity(x = y, id = "id", code = "code",
            map = "charlson_icd10_quan", assign0 = FALSE)
```
The full name is still COPD
<img width="276" alt="image" src="https://user-images.githubusercontent.com/59796224/161969343-e78b6ffe-3213-4644-ae32-3dd016d1cc21.png">
I look forward to your reply and thank you in advance.

**Comment by ellessenne** [comment]
> Sorry to remind you again. I just found an inconsistency, but I don't know the reason.

Thanks for catching that, labels are applied in a separate functions that I forgot to adjust. It should be fixed now.


> I noticed ami (acute myocardial infarction) is in Charlson comorbidity score. I checked the Quan (2005) again and I found he used MI (myocardial infarction) and I tried the codes of chronic myocardial infarction with I252 in the comorbidity( ). As a result, it was also counted as acute myocardial infarction, so I guess maybe the ami was made in the first version of this package, too.

Correct, that is now updated as well (`ami` to `mi`).

You can install the updated package with the same code from above, if you want to check it out:

```r
library(remotes)
remotes::install_github("ellessenne/comorbidity", ref = "#53")
```

Happy to hear more feedback if you have any!

**Comment by DrYan1102** [comment]
> 

Thank you for updating it so quickly. I have tried it just now, and it worked well. 
I feel so glad to use such an impressive package. Thank you for your work!

**Comment by ellessenne** [comment]
Super! Thanks very much for the feedback again, I will start drafting a new release for CRAN which should appear soon.
Best,

Alessandro
