### ISSUE TITLE
Conda-forge recipe.

### ISSUE THREAD

**Issue by abalter** [ellessenne/comorbidity#65]
Hello! I wanted to let you know that I created a recipe for this package in the "conda-forge" channel. This provides an alternate way to install it for people using conda for package management.

https://anaconda.org/conda-forge/r-comorbidity

https://github.com/conda-forge/r-comorbidity-feedstock

**Comment by ellessenne** [comment]
Thanks for the heads up. Does this require anything from my side to support it?

**Comment by abalter** [comment]
Not unless you want to take over. Maybe I should make an alert for updates here so I get notified if I should update the recipe?

**Comment by ellessenne** [comment]
That sounds good to me – I don't use conda so I don't want to officially take over supporting it, if you could keep that recipe up to date it'd be great, thanks!
