### ISSUE TITLE
Residual use of `ami` from #53

### ISSUE THREAD

**Issue by sciatro** [ellessenne/comorbidity#66]
The code group weights continue to refer to Acute MI (*ami*) vs the MI (*mi*) name change made to the codes in #53.

It looks like this is the case because https://github.com/ellessenne/comorbidity/commit/92d59b75c4343a0b959017e20676e54b29b1a645 touched `make-mapping.R` only vs. https://github.com/ellessenne/comorbidity/commit/6c1dac21d761f1597f8dbece2d8f4b7359f1b341 which touched both `make-mapping.R` and `make-weights.R`

I just happened to notice it in passing while tracking down an unexpected result that ultimately turned out to be the sub tree grepping described in #9. It is not obvious to me that this impacts function as it seems like weights are applied by order, not name, but it's easy to imagine confusion arising.

**Comment by ellessenne** [comment]
Good catch, thanks for pointing this out - I will fix this for the next release!
