### ISSUE TITLE
Using comorbidity 0.5.3

### ISSUE THREAD

**Issue by sk123-ux** [ellessenne/comorbidity#76]
Hello,

I want to use comorbidity 0.5.3 for a particular  dataset so I reverted the package to the older version using:

`remotes::install_github("ellessenne/comorbidity@0.5.3")`

However, when I try to use the older code (which displays the scores and weight scores as part of the mapping function) I encounter an error.

# Using newer code with comorbidity 0.5.3 works successfully
`com <- comorbidity(x = my_data, id = "SAMDS", code = "Code", map = "charlson_icd10_quan", assign0 = FALSE)
View(com)`

# Using older code with comorbidity 0.5.3 does not work and produces the following error
`com <- comorbidity(x = my_data, id = "SAMDS", code = "Code", score = "charlson", icd = "icd10", assign0 = FALSE)
View(com)`

`Error in comorbidity(x = sim_data, id = "SAMDS", code = "Code", score = "charlson",  : 
 unused arguments (score = "charlson", icd = "icd10")`

**Is there still a supported method of using comorbidity version 0.5.3?**

**Comment by ellessenne** [comment]
Hi, I cannot reproduce the issue but I suspect it may be enough to just restart your R session before installing the old version. Could you try that?

**Comment by sk123-ux** [comment]
Hello, yes it does. Thanks for your work on the package and for helping to fix this simple error.

**Comment by ellessenne** [comment]
That's good to hear, thanks for checking and confirming that!
