### ISSUE TITLE
testthat: no tests found

### ISSUE THREAD

**Issue by corinne-riddell** [ellessenne/comorbidity#8]
I've never used `testthat` before, so I may be doing something wrong. I cloned your repo and tried running the code in testthat.R and get the error: "Error: No tests found for comorbidity". However I was able to run the tests using `test_dir("./tests/testthat/")`. 

No sure if this error was the result of my misunderstanding/misuse, but wanted to note here how I enabled the tests to run.

Review Issue URL: https://github.com/openjournals/joss-reviews/issues/648

**Comment by ellessenne** [comment]
My workflow for running tests is:
1- Opening the RStudio project relative to the package
2- Run devtools::test()
Could you the same to see if it works for you?
Thanks!

**Comment by corinne-riddell** [comment]
That worked! I was prompted to install `roxygen2` and its dependencies, and after indicating Yes to installed, the packages installed and the tests ran. Maybe update the line in testthat.R to follow this workflow and include a comment re: opening the .Rproj file?

**Comment by ellessenne** [comment]
I think that the `testthat.R` file should not be touched, R CMD check is able to find and run the tests properly (see Hadley's bible on packages development: http://r-pkgs.had.co.nz/tests.html)!

**Comment by corinne-riddell** [comment]
I am illuminated 💡 ! Ok, sounds good.
